import type { CampaignChannel, ContentLanguage, EventCampaignItem, EventContentType, EventSummary, GenerateEventCampaignInput, GenerateEventContentInput } from "../shared/contracts.js";
import type { ConversationProviderRouter } from "./conversation-runtime.js";

const LABELS:Record<EventContentType,string>={EVENT_ANNOUNCEMENT:"Event announcement",ARTIST_ANNOUNCEMENT:"Artist announcement",LINEUP_REVEAL:"Lineup reveal",TICKET_PROMOTION:"Ticket promotion",GIVEAWAY:"Giveaway announcement",COUNTDOWN:"Countdown / last call",EVENT_DAY_INFO:"Event-day information",POST_EVENT_THANK_YOU:"Post-event thank-you"};
const OFFSETS:Array<[EventContentType,number]>=[["EVENT_ANNOUNCEMENT",-42],["LINEUP_REVEAL",-28],["ARTIST_ANNOUNCEMENT",-21],["TICKET_PROMOTION",-14],["COUNTDOWN",-3],["EVENT_DAY_INFO",0],["POST_EVENT_THANK_YOU",1]];
function atDay(date:string,offset:number,time="12:00"):string{const value=new Date(`${date}T${time}:00.000Z`);value.setUTCDate(value.getUTCDate()+offset);return value.toISOString();}
export function eventFacts(event:EventSummary):string{return [`Event: ${event.name}`,`Type: ${event.kind}`,`Date: ${event.date}`,`Timezone: ${event.timezone}`,`Venue: ${event.venue||"not provided"}`,`Address: ${event.address||"not provided"}`,`Organizer: ${event.organizer||"not provided"}`,`Genre: ${event.genre||"not provided"}`,`Description: ${event.description||"not provided"}`,`Lineup: ${event.lineup.map(slot=>`${slot.artistName}${slot.performanceStart?` (${slot.performanceStart})`:""}`).join(", ")||"not provided"}`,`Ticket URL: ${event.ticketUrl||"not provided"}`,`Event URL: ${event.eventUrl||"not provided"}`].join("\n");}
export function buildEventPrompt(event:EventSummary,input:GenerateEventContentInput):string{return `Create a ${LABELS[input.contentType]} for ${input.platform} in ${input.language.toUpperCase()}. Tone: ${input.tone||"clear and professional"}. Use ONLY the facts below. Never invent prices, lineup, venue details, rules, links or times. If a fact is missing, omit it. Return only publishable copy.\n\n${eventFacts(event)}`;}
export async function generateEventCopy(event:EventSummary,input:GenerateEventContentInput,router:ConversationProviderRouter):Promise<string>{const result=await router(buildEventPrompt(event,input));if(!result.ok||!result.output?.trim())throw new Error("Event content provider returned no usable content");return result.output.trim().slice(0,20000);}
export function buildEventCampaign(event:EventSummary,input:GenerateEventCampaignInput):Array<Omit<EventCampaignItem,"id"|"publishingQueueId"|"createdAt"|"updatedAt">>{const platforms=[...new Set(input.platforms)];if(!platforms.length)throw new Error("Select at least one campaign platform");return OFFSETS.flatMap(([contentType,offset],index)=>platforms.map((platform)=>({eventId:event.id,title:LABELS[contentType],contentType,language:input.language,platform,tone:input.tone,content:"",scheduledAt:atDay(event.date,offset,event.startTime??"12:00"),status:"DRAFT" as const}))).sort((a,b)=>(a.scheduledAt??"").localeCompare(b.scheduledAt??"")||a.platform.localeCompare(b.platform));}
