import { createHash, createHmac, randomUUID } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { safeStorage } from "electron";
import type { MediaBridgeStatus } from "../shared/contracts.js";

interface StoredBridge { accountId:string;bucket:string;accessKeyId:string;secretAccessKeyEncrypted:string; }
const region="auto",service="s3";
const hash=(value:string|Buffer)=>createHash("sha256").update(value).digest("hex");
const hmac=(key:string|Buffer,value:string)=>createHmac("sha256",key).update(value).digest();
const encode=(value:string)=>encodeURIComponent(value).replace(/[!'()*]/g,(char)=>`%${char.charCodeAt(0).toString(16).toUpperCase()}`);

export class MediaBridgeClient {
  private readonly filePath:string;private lastError:string|null=null;
  constructor(userDataPath:string){this.filePath=path.join(userDataPath,"integrations","media-bridge.json");}
  async status():Promise<MediaBridgeStatus>{const stored=await this.read();return{configured:Boolean(stored?.accountId&&stored.bucket&&stored.accessKeyId&&stored.secretAccessKeyEncrypted),provider:"cloudflare-r2",accountId:stored?.accountId??null,bucket:stored?.bucket??null,error:this.lastError};}
  async saveSettings(accountId:string,bucket:string,accessKeyId:string,secretAccessKey:string):Promise<MediaBridgeStatus>{if(!accountId.trim()||!bucket.trim()||!accessKeyId.trim()||!secretAccessKey.trim())throw new Error("All Cloudflare R2 fields are required");const value:StoredBridge={accountId:accountId.trim(),bucket:bucket.trim(),accessKeyId:accessKeyId.trim(),secretAccessKeyEncrypted:this.encrypt(secretAccessKey.trim())};await this.write(value);try{await this.request("HEAD",value,null,Buffer.alloc(0),"application/octet-stream");this.lastError=null;}catch(error){this.lastError=error instanceof Error?error.message:"R2 connection failed";throw error;}return this.status();}
  async stage(filePath:string,mimeType:string|null):Promise<{key:string;url:string}>{const stored=await this.requireConfigured(),extension=path.extname(filePath).toLowerCase()||".png",safeMime=mimeType??(extension===".jpg"||extension===".jpeg"?"image/jpeg":"image/png");if(!["image/png","image/jpeg"].includes(safeMime))throw new Error("Instagram Media Bridge V1 supports PNG and JPEG images only");const key=`ai-studio-manager/${new Date().toISOString().slice(0,10)}/${randomUUID()}${extension}`,bytes=await readFile(filePath);await this.request("PUT",stored,key,bytes,safeMime);return{key,url:this.presignedGet(stored,key,900)};}
  async remove(key:string):Promise<void>{const stored=await this.requireConfigured();await this.request("DELETE",stored,key,Buffer.alloc(0),"application/octet-stream");}
  private async request(method:"HEAD"|"PUT"|"DELETE",stored:StoredBridge,key:string|null,body:Buffer,mimeType:string):Promise<void>{const endpoint=this.endpoint(stored),url=new URL(key?`${endpoint}/${stored.bucket}/${this.objectPath(key)}`:`${endpoint}/${stored.bucket}`),now=new Date(),amzDate=now.toISOString().replace(/[:-]|\.\d{3}/g,""),date=amzDate.slice(0,8),payloadHash=hash(body),canonicalHeaders=`host:${url.host}\nx-amz-content-sha256:${payloadHash}\nx-amz-date:${amzDate}\n`,signedHeaders="host;x-amz-content-sha256;x-amz-date",canonicalRequest=[method,url.pathname,"",canonicalHeaders,signedHeaders,payloadHash].join("\n"),scope=`${date}/${region}/${service}/aws4_request`,stringToSign=["AWS4-HMAC-SHA256",amzDate,scope,hash(canonicalRequest)].join("\n"),signature=this.signature(this.decrypt(stored.secretAccessKeyEncrypted),date,stringToSign),authorization=`AWS4-HMAC-SHA256 Credential=${stored.accessKeyId}/${scope}, SignedHeaders=${signedHeaders}, Signature=${signature}`;const response=await fetch(url,{method,headers:{Authorization:authorization,"x-amz-date":amzDate,"x-amz-content-sha256":payloadHash,...(method==="PUT"?{"Content-Type":mimeType}:{})},body:method==="PUT"?new Uint8Array(body):undefined,signal:AbortSignal.timeout(60_000)});if(!response.ok)throw new Error(`Cloudflare R2 returned HTTP ${response.status}: ${(await response.text()).slice(0,300)}`);}
  private presignedGet(stored:StoredBridge,key:string,expires:number):string{const endpoint=this.endpoint(stored),url=new URL(`${endpoint}/${stored.bucket}/${this.objectPath(key)}`),now=new Date(),amzDate=now.toISOString().replace(/[:-]|\.\d{3}/g,""),date=amzDate.slice(0,8),scope=`${date}/${region}/${service}/aws4_request`,params:Record<string,string>={"X-Amz-Algorithm":"AWS4-HMAC-SHA256","X-Amz-Credential":`${stored.accessKeyId}/${scope}`,"X-Amz-Date":amzDate,"X-Amz-Expires":String(expires),"X-Amz-SignedHeaders":"host"},query=Object.entries(params).sort(([a],[b])=>a.localeCompare(b)).map(([name,value])=>`${encode(name)}=${encode(value)}`).join("&"),canonicalRequest=["GET",url.pathname,query,`host:${url.host}\n`,"host","UNSIGNED-PAYLOAD"].join("\n"),stringToSign=["AWS4-HMAC-SHA256",amzDate,scope,hash(canonicalRequest)].join("\n"),signature=this.signature(this.decrypt(stored.secretAccessKeyEncrypted),date,stringToSign);return `${url}?${query}&X-Amz-Signature=${signature}`;}
  private signature(secret:string,date:string,stringToSign:string):string{const dateKey=hmac(`AWS4${secret}`,date),regionKey=hmac(dateKey,region),serviceKey=hmac(regionKey,service),signingKey=hmac(serviceKey,"aws4_request");return createHmac("sha256",signingKey).update(stringToSign).digest("hex");}
  private endpoint(stored:StoredBridge):string{return `https://${stored.accountId}.r2.cloudflarestorage.com`;}
  private objectPath(key:string):string{return key.split("/").map(encode).join("/");}
  private async requireConfigured():Promise<StoredBridge>{const stored=await this.read();if(!stored)throw new Error("Configure Cloudflare R2 Media Bridge first");return stored;}
  private encrypt(value:string):string{if(!safeStorage.isEncryptionAvailable())throw new Error("Operating-system credential encryption is unavailable");return safeStorage.encryptString(value).toString("base64");}
  private decrypt(value:string):string{return safeStorage.decryptString(Buffer.from(value,"base64"));}
  private async read():Promise<StoredBridge|null>{try{return JSON.parse(await readFile(this.filePath,"utf8")) as StoredBridge;}catch(error){if((error as NodeJS.ErrnoException).code==="ENOENT")return null;throw error;}}
  private async write(value:StoredBridge):Promise<void>{await mkdir(path.dirname(this.filePath),{recursive:true});await writeFile(this.filePath,JSON.stringify(value,null,2),{encoding:"utf8",mode:0o600});}
}
