import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { safeStorage } from "electron";
import type { GeneratedMediaType, MediaGenerationSettings, MediaProvider } from "../shared/contracts.js";

interface StoredCredentials { openAiKeyEncrypted?:string; klingKeyEncrypted?:string; }
interface GenerationResult { providerTaskId?:string; remoteUrl?:string; bytes?:Buffer; mimeType?:string; metadata?:Record<string,unknown>; }

export class MediaGenerationClient {
  private readonly settingsPath:string;
  private readonly outputDirectory:string;
  constructor(userDataPath:string){this.settingsPath=path.join(userDataPath,"integrations","media-generation.json");this.outputDirectory=path.join(userDataPath,"generated-media");}
  async status():Promise<MediaGenerationSettings>{const stored=await this.readStored();return{openAiConfigured:Boolean(stored.openAiKeyEncrypted),klingConfigured:Boolean(stored.klingKeyEncrypted)};}
  async saveCredentials(openAiApiKey:string,klingApiKey:string):Promise<MediaGenerationSettings>{const current=await this.readStored();if(openAiApiKey.trim())current.openAiKeyEncrypted=this.encrypt(openAiApiKey.trim());if(klingApiKey.trim())current.klingKeyEncrypted=this.encrypt(klingApiKey.trim());await mkdir(path.dirname(this.settingsPath),{recursive:true});await writeFile(this.settingsPath,JSON.stringify(current,null,2),{mode:0o600});return this.status();}
  async generate(provider:MediaProvider,mediaType:GeneratedMediaType,prompt:string):Promise<GenerationResult>{const keys=await this.keys();if(provider==="openai"){if(mediaType!=="image")throw new Error("OpenAI is configured here for image generation. Use Kling for video.");if(!keys.openAi)throw new Error("Save an OpenAI API key in Integrations first");return this.generateOpenAiImage(keys.openAi,prompt);}if(!keys.kling)throw new Error("Save a Kling API key in Integrations first");return this.createKlingTask(keys.kling,mediaType,prompt);}
  async refreshKling(taskId:string,mediaType:GeneratedMediaType):Promise<GenerationResult|null>{const key=(await this.keys()).kling;if(!key)throw new Error("Kling API key is not configured");const route=mediaType==="video"?"videos/text2video":"images/generations";const response=await fetch(`https://api-singapore.klingai.com/v1/${route}/${encodeURIComponent(taskId)}`,{headers:{Authorization:`Bearer ${key}`}});const json=await response.json() as Record<string,any>;if(!response.ok||Number(json.code??0)!==0)throw new Error(`Kling API returned ${response.status}: ${String(json.message??json.msg??"request failed")}`);const data=json.data as Record<string,any>|undefined;const status=String(data?.task_status??data?.status??"").toLowerCase();if(["failed","error"].includes(status))throw new Error(String(data?.task_status_msg??data?.message??"Kling generation failed"));const resultUrl=mediaType==="video"?data?.task_result?.videos?.[0]?.url:data?.task_result?.images?.[0]?.url;if(!resultUrl)return null;return{providerTaskId:taskId,remoteUrl:String(resultUrl),metadata:{klingStatus:status}};}
  async saveRemoteResult(id:string,result:GenerationResult,mediaType:GeneratedMediaType):Promise<{localPath:string;mimeType:string;metadata:Record<string,unknown>}>{let bytes=result.bytes,mimeType=result.mimeType;if(!bytes&&result.remoteUrl){const response=await fetch(result.remoteUrl);if(!response.ok)throw new Error(`Could not download generated media (HTTP ${response.status})`);bytes=Buffer.from(await response.arrayBuffer());mimeType=response.headers.get("content-type")??undefined;}if(!bytes)throw new Error("Provider returned no downloadable media");const safeMime=mimeType?.split(";")[0]??(mediaType==="video"?"video/mp4":"image/png");const extension=safeMime.includes("jpeg")?"jpg":safeMime.includes("webp")?"webp":safeMime.includes("video")?"mp4":"png";await mkdir(this.outputDirectory,{recursive:true});const localPath=path.join(this.outputDirectory,`${id}.${extension}`);await writeFile(localPath,bytes);return{localPath,mimeType:safeMime,metadata:{...(result.metadata??{}),remoteUrl:result.remoteUrl??null}};}
  private async generateOpenAiImage(key:string,prompt:string):Promise<GenerationResult>{const response=await fetch("https://api.openai.com/v1/images/generations",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model:"gpt-image-1.5",prompt,size:"1024x1024",quality:"medium",output_format:"png"})});const json=await response.json() as Record<string,any>;if(!response.ok)throw new Error(`OpenAI API returned ${response.status}: ${String(json.error?.message??"request failed")}`);const item=json.data?.[0];if(item?.b64_json)return{bytes:Buffer.from(item.b64_json,"base64"),mimeType:"image/png",metadata:{model:"gpt-image-1.5",revisedPrompt:item.revised_prompt??null}};if(item?.url)return{remoteUrl:item.url,mimeType:"image/png",metadata:{model:"gpt-image-1.5"}};throw new Error("OpenAI returned no image data");}
  private async createKlingTask(key:string,mediaType:GeneratedMediaType,prompt:string):Promise<GenerationResult>{const route=mediaType==="video"?"videos/text2video":"images/generations";const body=mediaType==="video"?{model_name:"kling-v2-1-master",prompt,mode:"std",duration:"5",aspect_ratio:"9:16"}:{model_name:"kling-v1-5",prompt,n:1,aspect_ratio:"1:1"};const response=await fetch(`https://api-singapore.klingai.com/v1/${route}`,{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify(body)});const json=await response.json() as Record<string,any>;if(!response.ok||Number(json.code??0)!==0)throw new Error(`Kling API returned ${response.status}: ${String(json.message??json.msg??"request failed")}`);const taskId=json.data?.task_id;if(!taskId)throw new Error("Kling returned no task ID");return{providerTaskId:String(taskId),metadata:{klingStatus:"submitted"}};}
  private encrypt(value:string):string{if(!safeStorage.isEncryptionAvailable())throw new Error("Operating-system credential encryption is unavailable");return safeStorage.encryptString(value).toString("base64");}
  private decrypt(value?:string):string|undefined{return value?safeStorage.decryptString(Buffer.from(value,"base64")):undefined;}
  private async keys(){const stored=await this.readStored();return{openAi:this.decrypt(stored.openAiKeyEncrypted),kling:this.decrypt(stored.klingKeyEncrypted)};}
  private async readStored():Promise<StoredCredentials>{try{return JSON.parse(await readFile(this.settingsPath,"utf8")) as StoredCredentials;}catch{return{};}}
}
