import { randomBytes } from "node:crypto";
import { createServer } from "node:http";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { safeStorage, shell } from "electron";
import type { MetaConnection, MetaDestination } from "../shared/contracts.js";

const graphVersion="v26.0",callbackUrl="http://localhost:43822/callback";
interface StoredDestination extends MetaDestination { pageTokenEncrypted:string; }
interface StoredMeta { appId:string;appSecretEncrypted:string;userTokenEncrypted?:string;destinations?:StoredDestination[]; }

export class MetaClient {
  private readonly filePath:string;private pendingState:string|null=null;private lastError:string|null=null;
  constructor(userDataPath:string){this.filePath=path.join(userDataPath,"integrations","meta.json");}
  async status():Promise<MetaConnection>{const value=await this.read();return{configured:Boolean(value?.appId&&value.appSecretEncrypted),connected:Boolean(value?.userTokenEncrypted&&value.destinations?.length),callbackUrl,graphVersion,destinations:(value?.destinations??[]).map(({pageTokenEncrypted:_,...destination})=>destination),error:this.lastError};}
  async saveCredentials(appId:string,appSecret:string):Promise<MetaConnection>{if(!appId.trim()||!appSecret.trim())throw new Error("Meta App ID and App Secret are required");const current=await this.read();await this.write({...current,appId:appId.trim(),appSecretEncrypted:this.encrypt(appSecret.trim())});return this.status();}
  async beginConnect():Promise<void>{const stored=await this.requireConfigured();this.lastError=null;const state=randomBytes(24).toString("hex");this.pendingState=state;const server=createServer(async(request,response)=>{if(!request.url?.startsWith("/callback")){response.writeHead(404).end();return;}try{await this.handleCallback(new URL(request.url,callbackUrl));response.writeHead(200,{"Content-Type":"text/html; charset=utf-8"});response.end("<h1>Meta connected</h1><p>You can close this window and return to AI Music Manager.</p>");}catch(error){this.lastError=error instanceof Error?error.message:"Meta authorization failed";response.writeHead(400,{"Content-Type":"text/plain; charset=utf-8"});response.end(this.lastError);}finally{server.close();}});await new Promise<void>((resolve,reject)=>server.once("error",reject).listen(43822,"127.0.0.1",resolve));setTimeout(()=>{if(server.listening){this.lastError="Meta authorization timed out";server.close();}},180_000).unref();const url=new URL(`https://www.facebook.com/${graphVersion}/dialog/oauth`);url.search=new URLSearchParams({client_id:stored.appId,redirect_uri:callbackUrl,response_type:"code",state,scope:"pages_show_list,pages_read_engagement,pages_manage_posts,instagram_basic,instagram_content_publish"}).toString();await shell.openExternal(url.toString());}
  async disconnect():Promise<MetaConnection>{const stored=await this.read();if(stored)await this.write({appId:stored.appId,appSecretEncrypted:stored.appSecretEncrypted});return this.status();}
  async publishFacebook(destinationId:string,caption:string,mediaPath:string|null,mimeType:string|null):Promise<string>{const stored=await this.requireConnected(),destination=stored.destinations?.find((item)=>item.id===destinationId&&item.platform==="Facebook");if(!destination)throw new Error("Select a connected Facebook Page");const token=this.decrypt(destination.pageTokenEncrypted);if(mediaPath){const bytes=await readFile(mediaPath),form=new FormData();form.set("caption",caption);form.set("published","true");form.set("access_token",token);form.set("source",new Blob([bytes],{type:mimeType??"image/png"}),path.basename(mediaPath));return this.postId(`https://graph.facebook.com/${graphVersion}/${destination.pageId}/photos`,form);}const body=new URLSearchParams({message:caption,access_token:token});return this.postId(`https://graph.facebook.com/${graphVersion}/${destination.pageId}/feed`,body);}
  async publishInstagram(destinationId:string,caption:string,imageUrl:string):Promise<string>{const stored=await this.requireConnected(),destination=stored.destinations?.find((item)=>item.id===destinationId&&item.platform==="Instagram");if(!destination)throw new Error("Select a connected Instagram professional account");const token=this.decrypt(destination.pageTokenEncrypted),instagramId=destination.id.replace(/^instagram:/,"");const container=await this.postId(`https://graph.facebook.com/${graphVersion}/${instagramId}/media`,new URLSearchParams({image_url:imageUrl,caption,access_token:token}));for(let attempt=0;attempt<60;attempt++){await new Promise((resolve)=>setTimeout(resolve,2000));const status=await this.fetchJson(`https://graph.facebook.com/${graphVersion}/${container}?fields=status_code,status&access_token=${encodeURIComponent(token)}`) as {status_code?:string;status?:string};if(status.status_code==="FINISHED")return this.postId(`https://graph.facebook.com/${graphVersion}/${instagramId}/media_publish`,new URLSearchParams({creation_id:container,access_token:token}));if(["ERROR","EXPIRED"].includes(status.status_code??""))throw new Error(`Instagram media container failed: ${status.status??status.status_code}`);}throw new Error("Instagram media container did not become ready within 120 seconds");}
  private async handleCallback(url:URL):Promise<void>{const error=url.searchParams.get("error_description")??url.searchParams.get("error"),code=url.searchParams.get("code"),state=url.searchParams.get("state");if(error)throw new Error(`Meta authorization failed: ${error}`);if(!code||!state||state!==this.pendingState)throw new Error("Invalid or expired Meta callback");const stored=await this.requireConfigured(),secret=this.decrypt(stored.appSecretEncrypted);const short=await this.fetchJson(`https://graph.facebook.com/${graphVersion}/oauth/access_token?${new URLSearchParams({client_id:stored.appId,client_secret:secret,redirect_uri:callbackUrl,code})}`) as {access_token:string};const long=await this.fetchJson(`https://graph.facebook.com/${graphVersion}/oauth/access_token?${new URLSearchParams({grant_type:"fb_exchange_token",client_id:stored.appId,client_secret:secret,fb_exchange_token:short.access_token})}`) as {access_token:string};const pages=await this.fetchJson(`https://graph.facebook.com/${graphVersion}/me/accounts?fields=id,name,access_token,instagram_business_account{id,username}&limit=100&access_token=${encodeURIComponent(long.access_token)}`) as {data?:Array<{id:string;name:string;access_token:string;instagram_business_account?:{id:string;username?:string}}>};const destinations:StoredDestination[]=[];for(const page of pages.data??[]){destinations.push({id:`facebook:${page.id}`,platform:"Facebook",pageId:page.id,name:page.name,username:null,pageTokenEncrypted:this.encrypt(page.access_token)});if(page.instagram_business_account)destinations.push({id:`instagram:${page.instagram_business_account.id}`,platform:"Instagram",pageId:page.id,name:page.name,username:page.instagram_business_account.username??null,pageTokenEncrypted:this.encrypt(page.access_token)});}if(!destinations.length)throw new Error("Meta returned no manageable Facebook Pages. Check app permissions and account roles.");this.pendingState=null;await this.write({...stored,userTokenEncrypted:this.encrypt(long.access_token),destinations});}
  private async postId(url:string,body:FormData|URLSearchParams):Promise<string>{const response=await fetch(url,{method:"POST",body,signal:AbortSignal.timeout(60_000)}),text=await response.text();let json:Record<string,any>;try{json=JSON.parse(text) as Record<string,any>;}catch{json={};}if(!response.ok||json.error)throw new Error(`Meta API returned HTTP ${response.status}: ${String(json.error?.message??text.slice(0,300)??"request failed")}`);const id=json.post_id??json.id;if(!id)throw new Error("Meta accepted the request but returned no post ID");return String(id);}
  private async fetchJson(url:string):Promise<unknown>{const response=await fetch(url,{signal:AbortSignal.timeout(30_000)}),text=await response.text();if(!response.ok)throw new Error(`Meta API returned HTTP ${response.status}: ${text.slice(0,300)}`);return JSON.parse(text);}
  private async requireConfigured():Promise<StoredMeta>{const stored=await this.read();if(!stored?.appId||!stored.appSecretEncrypted)throw new Error("Save Meta App ID and App Secret first");return stored;}
  private async requireConnected():Promise<StoredMeta>{const stored=await this.requireConfigured();if(!stored.userTokenEncrypted||!stored.destinations?.length)throw new Error("Connect Meta first");return stored;}
  private encrypt(value:string):string{if(!safeStorage.isEncryptionAvailable())throw new Error("Operating-system credential encryption is unavailable");return safeStorage.encryptString(value).toString("base64");}
  private decrypt(value:string):string{return safeStorage.decryptString(Buffer.from(value,"base64"));}
  private async read():Promise<StoredMeta|null>{try{return JSON.parse(await readFile(this.filePath,"utf8")) as StoredMeta;}catch(error){if((error as NodeJS.ErrnoException).code==="ENOENT")return null;throw error;}}
  private async write(value:StoredMeta):Promise<void>{await mkdir(path.dirname(this.filePath),{recursive:true});await writeFile(this.filePath,JSON.stringify(value,null,2),{encoding:"utf8",mode:0o600});}
}
