import type { StudioApi } from "../shared/contracts.js";

const { contextBridge, ipcRenderer } = require("electron") as typeof import("electron");

const api: StudioApi = {
  getInterfacePreferences: () => ipcRenderer.invoke("studio:get-interface-preferences"),
  saveInterfacePreferences: (value) => ipcRenderer.invoke("studio:save-interface-preferences", value),
  sendConversationMessage: (input, onChunk) => {
    const listener = (_event: Electron.IpcRendererEvent, chunk: { requestId: string }) => { if (chunk.requestId === input.requestId) onChunk?.(chunk as never); };
    if (onChunk) ipcRenderer.on("studio:conversation-chunk", listener);
    return ipcRenderer.invoke("studio:send-conversation-message", input).finally(() => { if (onChunk) ipcRenderer.removeListener("studio:conversation-chunk", listener); });
  },
  cancelConversation: (requestId) => ipcRenderer.invoke("studio:cancel-conversation", requestId),
  runAiHarnessPlan: (input) => ipcRenderer.invoke("studio:run-ai-harness-plan", input),
  getHarnessExecutionContext: () => ipcRenderer.invoke("studio:get-harness-execution-context"),
  reviewHarnessExecution: (input) => ipcRenderer.invoke("studio:review-harness-execution", input),
  createHarnessExecutionApproval: (input) => ipcRenderer.invoke("studio:create-harness-execution-approval", input),
  executeHarnessTasks: (input) => ipcRenderer.invoke("studio:execute-harness-tasks", input),
  listHarnessExecutionAudit: () => ipcRenderer.invoke("studio:list-harness-execution-audit"),
  getSystemStatus: () => ipcRenderer.invoke("studio:get-system-status"),
  getDatabaseHealth: () => ipcRenderer.invoke("studio:get-database-health"),
  listReleases: () => ipcRenderer.invoke("studio:list-releases"),
  createReleaseDraft: (input) => ipcRenderer.invoke("studio:create-release-draft", input),
  updateRelease: (input) => ipcRenderer.invoke("studio:update-release", input),
  deleteRelease: (releaseId) => ipcRenderer.invoke("studio:delete-release", releaseId),
  listEvents:()=>ipcRenderer.invoke("studio:list-events"),
  getEvent:(id)=>ipcRenderer.invoke("studio:get-event",id),
  saveEvent:(input)=>ipcRenderer.invoke("studio:save-event",input),
  deleteEvent:(id)=>ipcRenderer.invoke("studio:delete-event",id),
  selectAndAttachEventAsset:(eventId,kind)=>ipcRenderer.invoke("studio:select-and-attach-event-asset",eventId,kind),
  detachEventAsset:(id)=>ipcRenderer.invoke("studio:detach-event-asset",id),
  listEventCampaignItems:(eventId)=>ipcRenderer.invoke("studio:list-event-campaign-items",eventId),
  generateEventContent:(input)=>ipcRenderer.invoke("studio:generate-event-content",input),
  generateEventCampaign:(input)=>ipcRenderer.invoke("studio:generate-event-campaign",input),
  updateEventCampaignItem:(id,input)=>ipcRenderer.invoke("studio:update-event-campaign-item",id,input),
  enqueueEventCampaignItem:(id)=>ipcRenderer.invoke("studio:enqueue-event-campaign-item",id),
  createReleasePlan: (input) => ipcRenderer.invoke("studio:create-release-plan", input),
  getReleasePlan: (id) => ipcRenderer.invoke("studio:get-release-plan", id),
  listReleasePlans: (releaseId) => ipcRenderer.invoke("studio:list-release-plans", releaseId),
  updateReleasePlan: (input) => ipcRenderer.invoke("studio:update-release-plan", input),
  changeReleasePlanStatus: (input) => ipcRenderer.invoke("studio:change-release-plan-status", input),
  createCampaignItem: (input) => ipcRenderer.invoke("studio:create-campaign-item", input),
  updateCampaignItem: (input) => ipcRenderer.invoke("studio:update-campaign-item", input),
  deleteCampaignItem: (id) => ipcRenderer.invoke("studio:delete-campaign-item", id),
  reorderCampaignItems: (input) => ipcRenderer.invoke("studio:reorder-campaign-items", input),
  recordApprovalAction: (input) => ipcRenderer.invoke("studio:record-approval-action", input),
  listApprovalRecords: (entityType, entityId) => ipcRenderer.invoke("studio:list-approval-records", entityType, entityId),
  generateReleasePlan: (input) => ipcRenderer.invoke("studio:generate-release-plan", input),
  regenerateReleasePlan: (input) => ipcRenderer.invoke("studio:regenerate-release-plan", input),
  getCurrentReleasePlan: (releaseId) => ipcRenderer.invoke("studio:get-current-release-plan", releaseId),
  approveReleasePlan: (input) => ipcRenderer.invoke("studio:approve-release-plan", input),
  getAiSettings: () => ipcRenderer.invoke("studio:get-ai-settings"),
  saveAiSettings: (settings) => ipcRenderer.invoke("studio:save-ai-settings", settings),
  generateCampaignDraft: (input) => ipcRenderer.invoke("studio:generate-campaign-draft", input),
  listDrafts: (releaseId) => ipcRenderer.invoke("studio:list-drafts", releaseId),
  saveGeneratedDraft: (input) => ipcRenderer.invoke("studio:save-generated-draft", input),
  updateDraftStatus: (draftId, status) => ipcRenderer.invoke("studio:update-draft-status", draftId, status),
  deleteDraft: (draftId) => ipcRenderer.invoke("studio:delete-draft", draftId),
  listAssets: (releaseId) => ipcRenderer.invoke("studio:list-assets", releaseId),
  selectAndAttachAsset: (releaseId, kind) => ipcRenderer.invoke("studio:select-and-attach-asset", releaseId, kind),
  detachAsset: (assetId) => ipcRenderer.invoke("studio:detach-asset", assetId),
  getAudioAnalysis: (assetId) => ipcRenderer.invoke("studio:get-audio-analysis", assetId),
  analyzeAudio: (assetId) => ipcRenderer.invoke("studio:analyze-audio", assetId),
  getAssetPlaybackUrl: (assetId) => ipcRenderer.invoke("studio:get-asset-playback-url", assetId),
  getReleaseReadiness: (releaseId) => ipcRenderer.invoke("studio:get-release-readiness", releaseId),
  listTasks: (releaseId) => ipcRenderer.invoke("studio:list-tasks", releaseId),
  createTask: (input) => ipcRenderer.invoke("studio:create-task", input),
  updateTaskStatus: (taskId, status) => ipcRenderer.invoke("studio:update-task-status", taskId, status),
  runTaskAgent: (taskId, model) => ipcRenderer.invoke("studio:run-task-agent", taskId, model),
  getSoundCloudConnection: () => ipcRenderer.invoke("studio:get-soundcloud-connection"),
  saveSoundCloudCredentials: (clientId, clientSecret) => ipcRenderer.invoke("studio:save-soundcloud-credentials", clientId, clientSecret),
  beginSoundCloudConnect: () => ipcRenderer.invoke("studio:begin-soundcloud-connect"),
  disconnectSoundCloud: () => ipcRenderer.invoke("studio:disconnect-soundcloud"),
  syncSoundCloudCatalog: () => ipcRenderer.invoke("studio:sync-soundcloud-catalog"),
  listSoundCloudTracks: () => ipcRenderer.invoke("studio:list-soundcloud-tracks"),
  updateSoundCloudTrack: (input) => ipcRenderer.invoke("studio:update-soundcloud-track", input),
  setSoundCloudTracksContentType: (ids, contentType) => ipcRenderer.invoke("studio:set-soundcloud-tracks-content-type", ids, contentType),
  linkSoundCloudTrack: (trackId, releaseId) => ipcRenderer.invoke("studio:link-soundcloud-track", trackId, releaseId),
  getSoundCloudTrackPerformance: (trackId) => ipcRenderer.invoke("studio:get-soundcloud-track-performance", trackId),
  getSpotifyConnection: () => ipcRenderer.invoke("studio:get-spotify-connection"),
  saveSpotifyClientId: (clientId) => ipcRenderer.invoke("studio:save-spotify-client-id", clientId),
  beginSpotifyConnect: () => ipcRenderer.invoke("studio:begin-spotify-connect"),
  disconnectSpotify: () => ipcRenderer.invoke("studio:disconnect-spotify"),
  getSpotifyArtistMappings: () => ipcRenderer.invoke("studio:get-spotify-artist-mappings"),
  saveSpotifyArtistMappings: (mappings) => ipcRenderer.invoke("studio:save-spotify-artist-mappings", mappings),
  syncSpotifyCatalog: () => ipcRenderer.invoke("studio:sync-spotify-catalog"),
  listSpotifyReleases: () => ipcRenderer.invoke("studio:list-spotify-releases"),
  linkSpotifyRelease: (spotifyReleaseId, releaseId) => ipcRenderer.invoke("studio:link-spotify-release", spotifyReleaseId, releaseId),
  getCatalogMatchSuggestions: () => ipcRenderer.invoke("studio:get-catalog-match-suggestions"),
  generateCampaignPack: (input) => ipcRenderer.invoke("studio:generate-campaign-pack", input),
  listCampaignPackItems: (releaseId) => ipcRenderer.invoke("studio:list-campaign-pack-items", releaseId),
  updateCampaignPackItemStatus: (itemId, status) => ipcRenderer.invoke("studio:update-campaign-pack-item-status", itemId, status),
  deleteCampaignPackItem: (itemId) => ipcRenderer.invoke("studio:delete-campaign-pack-item", itemId),
  getCampaignPackItemDependencyStatus: (itemId) => ipcRenderer.invoke("studio:get-campaign-pack-item-dependency-status", itemId),
  cleanupStaleMediaGenerations: (releaseId) => ipcRenderer.invoke("studio:cleanup-stale-media-generations", releaseId),
  getMediaGenerationSettings: () => ipcRenderer.invoke("studio:get-media-generation-settings"),
  saveMediaGenerationCredentials: (openAiApiKey, klingApiKey) => ipcRenderer.invoke("studio:save-media-generation-credentials", openAiApiKey, klingApiKey),
  testComfyUi: (comfyUiUrl) => ipcRenderer.invoke("studio:test-comfy-ui",comfyUiUrl),
  saveComfyUiSettings: (comfyUiUrl,checkpoint) => ipcRenderer.invoke("studio:save-comfy-ui-settings",comfyUiUrl,checkpoint),
  getKlingCliStatus: () => ipcRenderer.invoke("studio:get-kling-cli-status").catch(() => ({ available:false, version:null, account:null, error:"Kling CLI not consolidated yet â€” UI disabled" } as any)),
  getLocalServiceStatus: () => ipcRenderer.invoke("studio:get-local-service-status"),
  selectComfyUiLauncher: () => ipcRenderer.invoke("studio:select-comfy-ui-launcher"),
  setLocalServicesAutoStart: (enabled) => ipcRenderer.invoke("studio:set-local-services-auto-start",enabled),
  startLocalService: (service) => ipcRenderer.invoke("studio:start-local-service",service),
  stopLocalService: (service) => ipcRenderer.invoke("studio:stop-local-service",service),
  generateMedia: (input) => ipcRenderer.invoke("studio:generate-media", input),
  refreshMediaGeneration: (generationId) => ipcRenderer.invoke("studio:refresh-media-generation", generationId),
  listMediaGenerations: (releaseId) => ipcRenderer.invoke("studio:list-media-generations", releaseId),
  updateMediaGenerationStatus: (generationId, status) => ipcRenderer.invoke("studio:update-media-generation-status", generationId, status),
  getGeneratedMediaUrl: (generationId) => ipcRenderer.invoke("studio:get-generated-media-url", generationId),
  listPublishingQueue: () => ipcRenderer.invoke("studio:list-publishing-queue"),
  updatePublishingQueueStatus: (itemId,status) => ipcRenderer.invoke("studio:update-publishing-queue-status",itemId,status),
  reviewPublishingQueueItem: (input) => ipcRenderer.invoke("studio:review-publishing-queue-item", input),
  updatePublishingQueueContent: (input) => ipcRenderer.invoke("studio:update-publishing-queue-content", input),
  exportPublishingPack: (itemId) => ipcRenderer.invoke("studio:export-publishing-pack",itemId),
  listBrandProfiles: () => ipcRenderer.invoke("studio:list-brand-profiles"),
  updateBrandProfile: (input) => ipcRenderer.invoke("studio:update-brand-profile",input),
  listContacts: () => ipcRenderer.invoke("studio:list-contacts"),
  saveContact: (input) => ipcRenderer.invoke("studio:save-contact",input),
  deleteContact: (contactId) => ipcRenderer.invoke("studio:delete-contact",contactId),
  addContactInteraction: (input) => ipcRenderer.invoke("studio:add-contact-interaction",input),
  getMetaConnection: () => ipcRenderer.invoke("studio:get-meta-connection"),
  saveMetaCredentials: (appId,appSecret,configurationId) => ipcRenderer.invoke("studio:save-meta-credentials",appId,appSecret,configurationId),
  beginMetaConnect: () => ipcRenderer.invoke("studio:begin-meta-connect"),
  disconnectMeta: () => ipcRenderer.invoke("studio:disconnect-meta"),
  publishMetaQueueItem: (itemId,destinationId) => ipcRenderer.invoke("studio:publish-meta-queue-item",itemId,destinationId),
  publishMetaTestPost: (input) => ipcRenderer.invoke("studio:publish-meta-test-post",input).catch(() => ({ ok:false, platform:"Facebook", sanitizedError:"Meta test publish not consolidated â€” UI disabled" } as any)),
  getMediaBridgeStatus: () => ipcRenderer.invoke("studio:get-media-bridge-status"),
  saveMediaBridgeSettings: (accountId,bucket,accessKeyId,secretAccessKey) => ipcRenderer.invoke("studio:save-media-bridge-settings",accountId,bucket,accessKeyId,secretAccessKey),
  generatePromoContent: (input) => ipcRenderer.invoke("studio:generate-promo-content", input),
  listPromoGenerations: (releasePlanId) => ipcRenderer.invoke("studio:list-promo-generations", releasePlanId),
  retryPromoGeneration: (input) => ipcRenderer.invoke("studio:retry-promo-generation", input),
  updatePromoReview: (input) => ipcRenderer.invoke("studio:update-promo-review", input),
  editPromoContent: (input) => ipcRenderer.invoke("studio:edit-promo-content", input),
  deletePromoGeneration: (promoGenerationId) => ipcRenderer.invoke("studio:delete-promo-generation", promoGenerationId),
  createScheduleEvent: (input) => ipcRenderer.invoke("studio:create-schedule-event", input),
  updateScheduleEvent: (input) => ipcRenderer.invoke("studio:update-schedule-event", input),
  cancelScheduleEvent: (id) => ipcRenderer.invoke("studio:cancel-schedule-event", id),
  listScheduleEvents: (input) => ipcRenderer.invoke("studio:list-schedule-events", input),
  sendScheduleEventToPublishingQueue: (id) => ipcRenderer.invoke("studio:send-schedule-event-to-publishing-queue", id),
  listArtistPromotionProfiles: () => ipcRenderer.invoke("studio:list-artist-promotion-profiles").catch(() => [] as any),
  getArtistPromotionProfile: (artistId) => ipcRenderer.invoke("studio:get-artist-promotion-profile", artistId).catch(() => null as any),
  updateArtistPromotionProfile: (input) => ipcRenderer.invoke("studio:update-artist-promotion-profile", input).catch(() => Promise.reject(new Error("Artist promotion not consolidated"))),
beginPublishing: (itemId: string) => ipcRenderer.invoke("studio:begin-publishing", itemId),
  verifyPublishedPost: (itemId: string) => ipcRenderer.invoke("studio:verify-published-post", itemId),
  fetchAndStorePostAnalytics: (itemId: string) => ipcRenderer.invoke("studio:fetch-post-analytics", itemId),
  getAnalyticsSnapshots: (itemId: string) => ipcRenderer.invoke("studio:get-analytics-snapshots", itemId),
  getReleaseAnalyticsSummary: (releaseId: string) => ipcRenderer.invoke("studio:get-release-analytics-summary", releaseId),
  getYouTubeConnection: () => ipcRenderer.invoke("studio:get-youtube-connection"),
  saveYouTubeCredentials: (clientId, clientSecret) => ipcRenderer.invoke("studio:save-youtube-credentials", clientId, clientSecret),
  beginYouTubeConnect: () => ipcRenderer.invoke("studio:begin-youtube-connect"),
  disconnectYouTube: () => ipcRenderer.invoke("studio:disconnect-youtube"),
  publishYouTubeTest: (input) => ipcRenderer.invoke("studio:publish-youtube-test", input).catch(() => ({ ok:false, platform:"YouTube", sanitizedError:"YouTube test not consolidated" } as any)),
  selectYouTubeTestVideo: () => ipcRenderer.invoke("studio:select-youtube-test-video").catch(() => null as any),
  selectYouTubeTestThumbnail: () => ipcRenderer.invoke("studio:select-youtube-test-thumbnail").catch(() => null as any),
  getTikTokConnection: () => ipcRenderer.invoke("studio:get-tiktok-connection"),
  saveTikTokCredentials: (clientKey, clientSecret) => ipcRenderer.invoke("studio:save-tiktok-credentials", clientKey, clientSecret),
  beginTikTokConnect: () => ipcRenderer.invoke("studio:begin-tiktok-connect"),
  disconnectTikTok: () => ipcRenderer.invoke("studio:disconnect-tiktok"),
  getTikTokCreatorInfo: () => ipcRenderer.invoke("studio:get-tiktok-creator-info"),
  getTikTokUserProfile: () => ipcRenderer.invoke("studio:get-tiktok-user-profile"),
  publishTikTokTest: (input) => ipcRenderer.invoke("studio:publish-tiktok-test", input),
  selectTikTokTestVideo: () => ipcRenderer.invoke("studio:select-tiktok-test-video"),
  getYouTubeChannelData: () => ipcRenderer.invoke("studio:get-youtube-channel-data"),
  syncYouTubeChannelData: () => ipcRenderer.invoke("studio:sync-youtube-channel-data"),
  getYouTubeAnalytics: (range) => ipcRenderer.invoke("studio:get-youtube-analytics", range),
  syncYouTubeAnalytics: (range) => ipcRenderer.invoke("studio:sync-youtube-analytics", range),
  getDistroKidConnection: () => ipcRenderer.invoke("studio:get-distrokid-connection"),
  prepareDistroKidForm: (releaseId) => ipcRenderer.invoke("studio:prepare-distrokid-form", releaseId),
  openDistroKidUpload: (releaseId) => ipcRenderer.invoke("studio:open-distrokid-upload", releaseId),
  fillDistroKidForm: () => ipcRenderer.invoke("studio:fill-distrokid-form"),
  closeDistroKidSession: () => ipcRenderer.invoke("studio:close-distrokid-session")
};

contextBridge.exposeInMainWorld("studio", api);
