import { useState } from "react";
import type { CampaignItem, CampaignItemContentType, CampaignChannel } from "../../../electron/shared/contracts";
import { Button } from "../../ui/Button";
import { Input } from "../../ui/Input";
import { Select } from "../../ui/Select";
import { Textarea } from "../../ui/Textarea";
import { Toggle } from "../../ui/Toggle";

type CampaignItemEditorProps = { item?: CampaignItem; onSave: (data: { title: string; purpose: string; contentType: CampaignItemContentType; targetPlatforms: CampaignChannel[]; plannedDate?: string | null; plannedTime?: string | null; cta?: string; notes?: string; assetRequirements?: string[]; copyRequirements?: string[] }) => void; onCancel: () => void; busy: boolean; };
const CONTENT_TYPES: CampaignItemContentType[] = ["caption", "video-hook", "video-script", "image-prompt", "visualizer-prompt", "story", "email", "other"];
const PLATFORMS: CampaignChannel[] = ["Instagram", "Facebook", "TikTok", "SoundCloud", "YouTube"];

export function CampaignItemEditor({ item, onSave, onCancel, busy }: CampaignItemEditorProps) {
  const [title, setTitle] = useState(item?.title ?? ""); const [purpose, setPurpose] = useState(item?.purpose ?? ""); const [contentType, setContentType] = useState<CampaignItemContentType>(item?.contentType ?? "caption"); const [platforms, setPlatforms] = useState<CampaignChannel[]>(item?.targetPlatforms ?? ["Instagram"]); const [plannedDate, setPlannedDate] = useState(item?.plannedDate ?? ""); const [plannedTime, setPlannedTime] = useState(item?.plannedTime ?? ""); const [cta, setCta] = useState(item?.cta ?? ""); const [notes, setNotes] = useState(item?.notes ?? ""); const [assetRequirements, setAssetRequirements] = useState(item?.assetRequirements.join(", ") ?? ""); const [copyRequirements, setCopyRequirements] = useState(item?.copyRequirements.join(", ") ?? "");
  function togglePlatform(platform: CampaignChannel) { setPlatforms((previous) => previous.includes(platform) ? previous.filter((value) => value !== platform) : [...previous, platform]); }
  function handleSubmit(event: React.FormEvent) { event.preventDefault(); if (!title.trim() || platforms.length === 0) return; onSave({ title: title.trim(), purpose: purpose.trim(), contentType, targetPlatforms: platforms, plannedDate: plannedDate || null, plannedTime: plannedTime || null, cta: cta.trim() || undefined, notes: notes.trim() || undefined, assetRequirements: assetRequirements.split(",").map((value) => value.trim()).filter(Boolean), copyRequirements: copyRequirements.split(",").map((value) => value.trim()).filter(Boolean) }); }
  return <form className="rp-editor" onSubmit={handleSubmit}><div className="rp-editor-grid"><Input label="Title" required value={title} onChange={(event) => setTitle(event.target.value)} placeholder="e.g. Release announcement" /><Textarea label="Purpose" rows={2} value={purpose} onChange={(event) => setPurpose(event.target.value)} placeholder="What this item achieves in the campaign" /><Select label="Content type" value={contentType} onChange={(event) => setContentType(event.target.value as CampaignItemContentType)} options={CONTENT_TYPES.map((type) => ({ value: type, label: type }))} /><div className="rp-platform-picker"><span className="rp-platform-label">Target platforms</span><div className="rp-platform-options">{PLATFORMS.map((platform) => <Toggle key={platform} label={platform} checked={platforms.includes(platform)} disabled={busy} onChange={() => togglePlatform(platform)} />)}</div></div><Input label="Planned date" type="date" value={plannedDate} onChange={(event) => setPlannedDate(event.target.value)} /><Input label="Planned time" type="time" value={plannedTime} onChange={(event) => setPlannedTime(event.target.value)} /><Input label="Call to action" value={cta} onChange={(event) => setCta(event.target.value)} placeholder="e.g. Listen now" /><Textarea label="Notes" rows={2} value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="Internal notes for the artist" /><Input label="Asset requirements" value={assetRequirements} onChange={(event) => setAssetRequirements(event.target.value)} placeholder="Comma-separated: cover artwork, audio excerpt" /><Input label="Copy requirements" value={copyRequirements} onChange={(event) => setCopyRequirements(event.target.value)} placeholder="Comma-separated: short hook, visual cue" /></div><div className="rp-editor-actions"><Button variant="ghost" onClick={onCancel} disabled={busy}>Cancel</Button><Button type="submit" disabled={busy || !title.trim() || platforms.length === 0}>{busy ? "Saving..." : item ? "Save changes" : "Add item"}</Button></div></form>;
}
