import { useEffect, useRef, useState } from "react";

export function AudioPlayer({ source, title }: { source: string; title: string }) {
  const audio=useRef<HTMLAudioElement>(null); const [playing,setPlaying]=useState(false),[current,setCurrent]=useState(0),[duration,setDuration]=useState(0),[volume,setVolume]=useState(.8),[error,setError]=useState("");
  useEffect(()=>{setPlaying(false);setCurrent(0);setDuration(0);setError("");},[source]);
  const time=(value:number)=>Number.isFinite(value)?`${Math.floor(value/60)}:${Math.floor(value%60).toString().padStart(2,"0")}`:"0:00";
  async function toggle(){const element=audio.current;if(!element)return;if(element.paused){try{await element.play();}catch{setError("This audio format could not be played by Chromium.");}}else element.pause();}
  return <div className="audio-player"><audio ref={audio} src={source} preload="metadata" onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onTimeUpdate={(event)=>setCurrent(event.currentTarget.currentTime)} onLoadedMetadata={(event)=>setDuration(event.currentTarget.duration)} onEnded={()=>setPlaying(false)} onError={()=>setError("Preview unavailable. The original file remains unchanged.")} /><button className="player-toggle" onClick={()=>void toggle()} aria-label={playing?"Pause":"Play"}>{playing?"Ⅱ":"▶"}</button><div className="player-body"><div className="player-title"><strong>{title}</strong><span>{time(current)} / {time(duration)}</span></div><input aria-label="Playback position" type="range" min="0" max={duration||0} step="0.1" value={Math.min(current,duration||0)} onChange={(event)=>{const value=Number(event.target.value);if(audio.current)audio.current.currentTime=value;setCurrent(value);}} /><div className="player-volume"><span>VOL</span><input aria-label="Volume" type="range" min="0" max="1" step="0.01" value={volume} onChange={(event)=>{const value=Number(event.target.value);setVolume(value);if(audio.current)audio.current.volume=value;}} /></div>{error&&<small>{error}</small>}</div></div>;
}
